on:
  release:
    types:
      - published
      - prereleased

name: Notify Discord about latest release

jobs:
  build:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        uses: sarisia/actions-status-discord@v1.10.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "Notify"
          description: "Can you show me?"
          color: 0x00ff00
          username: GitHub Actions