# Simple workflow for deploying static content to GitHub Pages
name: Deploy Flutter for Web to GitHub Pages

on:
  # Triggerd from Codemagic workflow
  repository_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo ::set-output name=repository::$REPOSITORY
      - name: echo build_number
        run: echo ${github.event.client_payload.build_number}
      - name: Build Flutter for Web
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      #- run: flutter gen-l10n
      #- run: flutter pub run icons_launcher:create
      #- run: flutter pub run flutter_native_splash:create
      - run: flutter build web --release --build-number=${github.event.client_payload.build_number}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './build/web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
